---
version: '2.1'
services:
  db:
    image: registry.opensuse.org/obs/server/unstable/container/leap153/containers/openbuildservice/mariadb
    command: /usr/lib/mysql/mysql-systemd-helper start
  cache:
    image: registry.opensuse.org/obs/server/unstable/container/leap153/containers/openbuildservice/memcached
    command: /usr/sbin/memcached -u memcached
  backend:
    image: registry.opensuse.org/obs/server/unstable/container/leap153/containers/openbuildservice/backend
    command: /obs/contrib/start_development_backend -d /obs
    volumes:
    - .:/obs
  worker:
    image: registry.opensuse.org/obs/server/unstable/container/leap153/containers/openbuildservice/backend
    volumes:
    - .:/obs
    privileged: true
    depends_on:
    - backend
    command: /obs/contrib/start_development_worker
  frontend:
    user: frontend
    image: registry.opensuse.org/obs/server/unstable/container/leap153/containers/openbuildservice/frontend-base
    networks:
    - traefik
    - default
    command: /obs/contrib/entrypoint.sh
    volumes:
    - .:/obs
    environment:
    - RAILS_RELATIVE_URL_ROOT={{ root_url }}
    labels:
      traefik.frontend.rule: {{ traefik_frontend_rule }}
      traefik.docker.network: traefik_default
      traefik.port: '3000'
    depends_on:
    - db
    - cache
    - backend
    - worker
networks:
  traefik:
    external:
      name: traefik_default
